- name: Create /srv/cloud-1
  ansible.builtin.file:
    path: "{{ install_dir }}"
    state: directory

- name: Install docker-compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ install_dir }}/docker-compose.yml"